### ISSUE TITLE
Reaction rates output

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#318]
There seem to be discrepancies between `instantaneousRates/` and `lossRates.output`/`productionRates.output`. Need to check:
1. that the calculation is the same for both
1. that the calculation is correct
1. that the correct values are output

**Comment by rs028** [comment]
@spco sorry to spring this on you, but can you prioritize this when you have free time from the other projects? Thanks

**Comment by spco** [comment]
Sure - can you give me an example where there is a discrepancy? Preferably in the behavioural testsuite. or with other inputs if it's not seen in the testuite.

**Comment by spco** [comment]
Taking a look at the source code, I'm not surprised that there is discrepancy - they are measuring different things. Perhaps it would be useful to know what you're expecting that they should report (in words, not numerics), and then I can compare to that?

**Comment by rs028** [comment]
in `spec_yes_env_no_with_jfac`: reaction 16 is 1.511860E9 in `lossrates.output` but 110858.18241622859 in `36400.cmp`, while reaction 17 is the same in both files.

I see now your comment. They are different how?

**Comment by spco** [comment]
Ok, so this is what currently happens. The key lines are `solverFunctions.f90:59-74`.

Line 59 calls `mechanism_rates()`. this fills `r`, a vector with as many elements as there are equations in the .fac file, with the base rate coefficients for that equation - the number given in the .fac file for that equation.

Loop 1 (L61-64) loops over each reactant in each equation. L62 multiplies each element of `r` by the current concentration of each reactant species in that reaction. So now we have what I'll call the 'actual rate' of the equation: this is the actual rate of the equation, taking into account the current concentrations of each species.
`instantaneousRates` is updated to contain a copy of `r` at this point - so the contents of `instantaneousRates/3600` for example contain this value as evaluated at time 3600. So far so good. I hope that makes sense.

Loops 2 (L66-69) and 3 (L71-74) are less straightforward, and at least one is wrong - possibly both.

L67 in loop 2 adds the contribution from each reactant in each equation, and maps it into `dy`. `dy` contains one element per species, and is what will be used in the time integration. So this subtracts the contribution of each reactant in each element. So at this point, `dy` contains all the negative contributions to each species.

If we skip forward to L72 now, then exactly the same happens in this loop, but looping over all the products in each reaction. By the end of this loop, `dy` contains the instantaneous rate of change for each species at this time - it is the sum of all the production minus all the consumption.

---
### Summary so far

So I'm happy with the calculation of `dy` throughout. Nothing is wrong with this, which is used in the time integration - our results are basically sound in this regard.

---

## Where it starts to go wrong...

But the calculation of `lossRates` and `productionRates` is wrong, and I'm not entirely sure what's desired either.

Let's start with what the output format is: we have a list of species of interest. For each occurence of each of these species in each reaction, we have a line containing this occurence and associated data: the species name and number, the reaction number and string, and the current time. Finally, we have the 'rate' column. Given the format of the rest of the file, I presume this rate is supposed to contain the instantaneous rate of change of this species due to this reaction. So if we summed all the lines associated to this species in both the product and loss output files, we would expect to arrive at the value in the element of `dy` associated to this species. Do you agree with this assessment of what this output file should hold?

As for what is currently being output: the calculation of `lossRates` vector looks nonsensical currently: in L68, `lhs(1,i)` on the left is an index to an equation number, but `lhs(2,i)` on the right is an index to a species number. This means I can't see this line making much sense.

The calculation of `productionRates` may or may not be right - it looks like it's being filled with the sum of rates of each product for each equation, which also doesn't make much sense.

If these should be filled as I suggest 3 paragraphs up, then I don't think we want to be summing anything.

Could you advise particularly on what you _expect_ these files to be telling you? I can work from there, but it certainly looks like at least one, and probably both, of these is wrong. As always, I'm free most of the day for most days this week if it would be easier to talk this over in person.

**Comment by rs028** [comment]
I am closing this, since it is being discussed in #319.
