### ISSUE TITLE
Fruit configuration

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#338]
Need a better way to configure `travis/unit_tests/fruit_generator.rb`: at the moment it is being picked up by git because it is different than the default version (similar problem as `Makefile`).

Also, what are the requirement? Ruby? Rake? Both? Any particular version of them?

**EDIT:** could `fruit_generator.rb` be automatically generated by `Makefile` when `make unittests` is executed? Would it make sense?

**Comment by spco** [comment]
I have run 
```
git update-index --skip-worktree travis/unit_tests/fruit_generator.rb 
```
to stop git following any updates to `fruit_generator.rb` - this keeps it in the repository (so new clones of the repo will get a copy), but ignores any changes you make to it. This is preferable to placing it in `.gitignore`, because that would remove it from the repo.

Each user has to run this once after they clone (if it's an issue for them at all) but that's all.

As for requirements, I'm not sure of the full range of support, but on my Mac I have Ruby 2.4.2, Travis Mac uses 2.4.3, and 2.4.1 on Travis Linux. So I guess that's a range already that seems to work ;) We don't need rake, as we use Make instead - I made that conscious choice to reduce the added dependencies :) 

Does that make sense? And is that fix for `fruit_generator.rb` an ok one? I guess it might be good to document that in the wiki under the install, or under a bit about development.

**Comment by rs028** [comment]
Yes, that works for us, but I was also thinking in terms of ease of configuration for a new user. The only thing that needs to be changed is `~/atchem-libraries/` on line 4 of the file (`load "~/atchem-libraries/fruit_3.4.3/rake_base.rb"`).

But that info is already in the `Makefile`  in the `FRUITDIR` variable. Basically we are asking the user to set `FRUITDIR` in two different files. No big deal, sure, but how about using a `sed` instruction in the `Makefile` before using `fruit_generator.rb`?

For the requirements, okay, I want to do a fresh install of everything and will update the wiki as I do it, from the perspective of a new user.

**Comment by rs028** [comment]
This is sorted.

@spco On this subject, now that you have done a few of these unit tests, do you think it is a better (ie, faster or more efficient or more accurate) way to do the testing?

**Comment by rs028** [comment]
Okay. Just wanted to understand if it was worth going through the trouble of implementing the whole framework :)
