### ISSUE TITLE
Improve support for ifort

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#398]
- compilation flags in `Makefile`
- Travis testing

Other compilers? g95?

**Comment by spco** [comment]
Due to compiler licensing issues, I don't expect this to be very workable on GitHub Actions (or on Travis or other alternatives). But it might be good to decide which flags are needed to run locally under ifort.

**Comment by rs028** [comment]
That sounds like a reasonable compromise to me.

What about g95? I know some people prefer it to gfortran.

**Comment by spco** [comment]
I don't know - g95 is no longer maintained (since 2013) so its userbase is probably pretty low these days, and it won't have some of the newer features (not that I think we use them anyway). `gfortran` was originally a 2003 fork of g95, so they are quite closely related.

Essentially, I have no objection to this being added, but I don't see it as high-priority for myself :)

**Comment by rs028** [comment]
I didn't know it was abandoned. ok then. Let's say we just set the correct flags for ifort and that's it for this issue.

**Comment by rs028** [comment]
I update this issue to add a couple of versions of `gfortran` (since version 8 was removed with #455, only version 9 is being tested now).

**Comment by spco** [comment]
#456 now fixes this so that gfortran-8 is once again being tested on both OSs

**Comment by rs028** [comment]
Awesome!

**Comment by rs028** [comment]
Solved by PR #496.
