### ISSUE TITLE
Reactions with no reactants

### ISSUE THREAD

**Issue by mpanagi** [AtChem/AtChem2#413]
When you write reactions with no reactants the model doesn't run.

You need to give a reactant name (e.g. EMISSIONS) to run the model

**Comment by rs028** [comment]
To expand on this:

The reaction:

    % k : = A;

creates an error in `mechanism.species`. This is not the case when the products are missing (eg, `% k : A = ;`) which seems to be working fine.

A reaction with no reactants can be used to simulate emissions and one workaround this problem is to create a fake species with a very large constant value and use it as a "reactant". This is not ideal, the python script should be able to deal with missing reactants as it does with missing products.

**Comment by spco** [comment]
Ok - so is it that `mech_converter.py` either errors or creates a malformed `mechanism.species`, or is it that AtChem can't handle it, even though it is perfectly well formed?

**Comment by rs028** [comment]
I think it is a malformed `mechanism.species`. It looks like this:

```
A
B

C
```

and probably the system does not like the empty line. @mpanagi  can you confirm?

**Comment by rs028** [comment]
I have a done a simple test using the following basic mechanism:
```
% 1 : A + B = C ;                                                                             
% 2 : = D ;                                                                                   
% 3 : E + F = G ;                                                                             
% 4 : H = ;
```

The files `mechanism.reac`
```
9 4 0 numberOfSpecies numberOfReactions numberOfGenericComplex
1 1
1 2
2 4
3 6
3 7
4 9
```

 and `mechanism.prod`:
```
9 4 0 numberOfSpecies numberOfReactions numberOfGenericComplex
1 3
2 5
3 8
```

both seem correct. The file `mechanism.species` however is not:
```
1 A
2 B
3 C
4 
5 D
6 E
7 F
8 G
9 H
```
What I don't understand is why reaction 2 causes a problem but reaction 4 does not. Trying to locate the point of `mech_converter.py` where this happens.

**Comment by spco** [comment]
I don't have time to fully test this, but I believe the issue is at https://github.com/AtChem/AtChem2/blob/057fdffe52ad3e95208314a38a64318db1296b02/build/mech_converter.py#L325 
`reactantsList` is ' ' (one space) rather than the empty string, so it's entering the body of the if statement when it shouldn't. It should be fixable with 
```
if not reactantsList == '' and not reactantsList.isspace():
```
or similar, but I haven't fully tested that.

The key is that in `mechanism.reac` there shouldn't be the line `2 4` - it's errantly treating a space ' ' as a species name, so in the corrected version all the species numbers change.

Hope that gets most of the way there?

**Comment by spco** [comment]
In fact, it might be neater to try `if not reactantsList.strip() == '':`

**Comment by rs028** [comment]
I think that does it! I also added it to `productsList` as a safeguard, although when the products are missing there is no error. Thank you so much.
