### ISSUE TITLE
test suite messages

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#423]
Improve the test suite messages. There need to be a summary printed to screen with the results of all the tests being run, including the unit tests. At the moment each group of tests has its indivifual summary and it gets lost in the long printouts of the following tests.

Also, FRUIT does not creat a logfile if it fails like the other tests do. Another option to consider is to always create logfiles, not just when there is a failure.

**Comment by rs028** [comment]
@spco Does implementation of GH Actions make it easier to implement this?

**Comment by spco** [comment]
Not that I'm aware of, because in our case Actions is just a vanilla layer sitting underneath, and we control the testsuite ourselves (some Actions for other languages are much more integrated than this, but the Fortran support isn't there so we have to use a vanilla one). So work on this would likely just be changing our own bash scripts etc.

**Comment by rs028** [comment]
Solved by PR #496.
