### ISSUE TITLE
Issue with cvode

### ISSUE THREAD

**Issue by Jkhadgi** [AtChem/AtChem2#462]
Tried to install the cvode from install directory to the library directory

 
![image](https://user-images.githubusercontent.com/84034928/146851333-ab78f788-0bd4-4243-b5f0-1707e0a220f1.png)

I tried to add the path for  for the LAPACK in install_cvode.sh
 
![image](https://user-images.githubusercontent.com/84034928/146851372-f676ffd1-9e7a-4877-9f46-1a48a29e6573.png)

But, it generated same error as above
Shall I try to install manually cvode from source??

**Comment by rs028** [comment]
Hi @Jkhadgi do you have all the requirements installed (gfortran, cmake, make)?
Can you try with the development version (https://github.com/AtChem/AtChem2/archive/refs/heads/master.zip) instead of the stable release?

**Comment by Jkhadgi** [comment]
I actually replaced the cmake with ccmake in line 72 in install_cvode.sh and it worked!!!

**Comment by rs028** [comment]
@spco what do you think about that?

**Comment by spco** [comment]
Hi all. I'm not certain as it stands, but could I ask you to 
(a) tell me the version numbers of `cmake` and `ccmake` you're using;
(b) tell me the OS you're using; and 
(c) try running with `cmake` and using the explicit path rather than relying on tilde expansion. So that would be something like
`./tools/install/install_cvode.sh /Users/jkhadgi/library` or `./tools/install/install_cvode.sh /home/jkhadgi/library` depending on your OS.

Some versions of cmake don't expand the tilde, so it _might_ be that. Thanks!

**Comment by spco** [comment]
Great! Glad to hear. Thanks for the update
