### ISSUE TITLE
Mechanism file error

### ISSUE THREAD

**Issue by tanzinaakther** [AtChem/AtChem2#489]
Hi, I was running the model fine. Now I wanted to add more mechanisms. So, I downloaded new mechanism file and I am getting this error. Any idea why I am getting this error?
<img width="777" alt="mechanism file error" src="https://user-images.githubusercontent.com/123010272/227011310-453ce6e5-82ed-4c76-b1ec-1056bfa71567.PNG">
<img width="778" alt="run error" src="https://user-images.githubusercontent.com/123010272/227011315-eccc0fd4-6ded-49e9-864d-756fd74eaf13.PNG">

**Comment by spco** [comment]
Reading your error message - please show us the contents of `/home/takther/Model_03/AtChem2_Tanzina/model_rns/constratints/species/NC4H10` - if you're able to upload the file here that would be particularly helpful.

**Comment by rs028** [comment]
The first error is just a warning. It means that you have two species in your RO2 summation that are not actually peroxy radicals. This is an error of the MCM database. Manually delete `IPRCHOO` and `IPRCHOOA` from the RO2 summation in the `.fac` file and it will be okay.

**Comment by tanzinaakther** [comment]
> Reading your error message - please show us the contents of `/home/takther/Model_03/AtChem2_Tanzina/model_rns/constratints/species/NC4H10` - if you're able to upload the file here that would be particularly helpful.

I removed NC4H10 as there were 0 values in the file.

**Comment by spco** [comment]
The latest error indicates that the linear interpolation of one of the constraints has failed. This is usually because the time interval over which the constraints is defined does not contain the time at which interpolation is taking place.

Please check that all of your constraints files define a value from 0 until the end of the time interval being calculated. It is worth defining the constraints until a little _after_ the end of the time interval, because occasionally the algorithm overshoots the desired end time by a small amount.

If NC4H10 is meant to be constrained, then please ensure it _does_ have a file associated to it, _and_ it is present in `speciesConstrained.config`. If it's not meant to be constrained, then make sure it doesn't have a file _and_ isn't present in `speciesConstrained.config`. If you only have one of those 2 conditions, then you will get such an error.

**Comment by rs028** [comment]
@spco, this should probably be addressed somehow at some point. It is perhaps part of issue #348 - I will add a note there.

**Comment by tanzinaakther** [comment]
I thought maybe this problem is related to new mechanism file I downloaded. But I am getting the same error using my previous mechanism file. I even deleted all the constrained species name from the species constrained.config file and only wrote one speicies to check if it runs. But the same error.

**Comment by rs028** [comment]
Can you run the tests?

**Comment by tanzinaakther** [comment]
which one you are referring as test? Today I only downloaded C3H8 mechanism and try to run but same problem.

**Comment by rs028** [comment]
You should be able to run `make oldtests` if the model is installed properly.

**Comment by rs028** [comment]
Try `make clean` and recompile the model and see if it solves the issue

**Comment by tanzinaakther** [comment]
Sure. Thank you

**Comment by rs028** [comment]
@tanzinaakther Did you manage to resolve this problem?
