### ISSUE TITLE
Using the AtChem2 model to study the sensitivity of ozone production.

### ISSUE THREAD

**Issue by brian981212** [AtChem/AtChem2#491]
Hello, I am currently using the AtChem2 model to study the sensitivity of ozone production. I would like to ask, if I want to use relative incremental reactivity to determine which class of precursors ozone is sensitive to, which species do I need to constrain in my model? I have data on ozone, carbon monoxide, nitrogen monoxide, nitrogen dioxide, sulfur dioxide, VOCs, temperature, air pressure, and relative humidity.

**Comment by brian981212** [comment]
> Hi @brian981212 this is more a matter of what your modelling objectives are, and the kind of data you have. I would suggest you have a look at the published literature to see how AtChem has been used to answer specific questions.
Thank you very much for your answer. I will go and look at the relevant literature. I have this question because I saw in #461 that you answered "Also be careful that the model must NOT be constrained to O3 and/or NO otherwise the results won't make sense." I don't understand why constraining ozone and nitrogen monoxide would lead to meaningless results, so I came to ask you. It seems that I have a similar question to the one in #461."

**Comment by rs028** [comment]
It does depend on what you want to do. That question in 461 was about calculating O3 loss rate which does depend on O3 and NO concentrations so it doesn't really make sense to constrain these species.
In your case, if you are constraining O3 , the model won't be able to tell you how O3 concentration changes when there is a change in, e.g., a given VOC, because the concentration is forced to the constrained value. You have to think which species/parameters need to be forced to have certain values and which you need to allow the model to calculate freely, depending on the problem you are trying to solve. Hope this makes sense.
I am going to close this issue now, because it is not really about AtChem2, but feel free to drop me an email if you have further questions.
